### ISSUE TITLE
is this project working?

### ISSUE THREAD

**Issue by grmkris** [juliuskrah/jasper-html-mail#1]
Hi mate I am developing something similar and I've used lots of your code as inspiration. But now i am wondering whether you forgot to commit some stuff?
Will try to pull your project and run it to see if it actually works

**Comment by juliuskrah** [comment]
The code works. Clone the repository and run

**Comment by lyankyaw28** [comment]
how to run?

**Comment by juliuskrah** [comment]
@lyankyaw28 From the root of the project, run the following command `mvn clean spring-boot:run`. This assumes that you have Maven installed
